{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c67bcf9a",
   "metadata": {},
   "source": [
    "**Q1. What are the two latest user-defined exception constraints in Python 3.X?**\n",
    "\n",
    "**Ans:** `raise` and `assert`\n",
    "\n",
    "**Q2. How are class-based exceptions that have been raised matched to handlers?**\n",
    "\n",
    "**Ans:** When a class-based exception is raised in Python, the interpreter looks for an appropriate exception handler to handle the exception. The search begins with the innermost try statement and progresses to the outermost try statement; if no appropriate handler is found, the programÂ is terminated and a traceback is printed.\n",
    "\n",
    "When an exception is raised, the interpreter checks the class of the exception against the classes of the handlers in the current call stack. The search starts with the innermost try statement and proceeds to the outermost try statement until a handler is found that matches the exception's class or a superclass of the exception's class.\n",
    "\n",
    "For Example:\n",
    "\n",
    "```python\n",
    "class MyException(Exception):\n",
    "    pass\n",
    "\n",
    "try:\n",
    "    raise MyException(\"This is my exception\")\n",
    "except ValueError:\n",
    "    print(\"Caught a ValueError\")\n",
    "except MyException:\n",
    "    print(\"Caught a MyException\")\n",
    "```\n",
    "\n",
    "In this code, a `MyException` object is raised, the interpreter searches for an appropriate handler to handle it. Since there is no `ValueError` handler, the interpreter moves on to the next handler and finds the `MyException` handler, which matches the class of the exception and prints \"Caught a MyException\".\n",
    "\n",
    "**Q3. Describe two methods for attaching context information to exception artefacts.**\n",
    "\n",
    "**Ans:** \n",
    "1. Using exception arguments: When raising an exception in Python, one way to attach context information is to pass the relevant information as **arguments**. For example, if you raise a `ValueError` exception because of an invalid argument, you can pass the invalid argument to the exception as an argument. When the exception is caught and processed, the context information is readily available in the exception object's arguments.\n",
    "\n",
    "```python\n",
    "try:\n",
    "    # some code that might raise an exception\n",
    "    raise ValueError(\"Something went wrong\", {\"key\": \"value\"})\n",
    "except ValueError as e:\n",
    "    print(e.args) #args includes error message and additional data \n",
    "```\n",
    "\n",
    "2. Using exception attributes: Setting **attributes on the exception object** is another way to attach context information to an exception. This method enables you to add arbitrary data to the exception object, which can then be used to provide additional context to the exception. You could, for example, create a custom exception class and add attributes to it to store pertinent context information. When an exception is caught and processed, the context information can be accessed via the exception object's attributes.\n",
    "\n",
    "```python\n",
    "class MyException(Exception):\n",
    "    def __init__(self, message, context=None):\n",
    "        super().__init__(message)\n",
    "        self.context = context\n",
    "\n",
    "try:\n",
    "    # some code that may raise an exception\n",
    "    raise MyException(\"An error occurred\", {\"user\": \"John\", \"action\": \"login\"})\n",
    "except MyException as e:\n",
    "    print(e.context) #context includes error message and additional data \n",
    "```\n",
    "\n",
    "**Q4. Describe two methods for specifying the text of an exception object's error message.**\n",
    "\n",
    "**Ans:** Below are two ways for specifying the text of an exception object's error message:\n",
    "\n",
    "1. Passing the error message as arguments to exception constructor.\n",
    "\n",
    "```python\n",
    "raise ValueError(\"Invalid input...\")\n",
    "```\n",
    "\n",
    "2. Defining a custom exception class with a message attribute.\n",
    "```python\n",
    "class MyException(Exception):\n",
    "    message = \"An error occurred\"\n",
    "\n",
    "try:\n",
    "    # some code that may raise an exception\n",
    "    raise MyException\n",
    "except MyException as e:\n",
    "    print(e.message) \n",
    "```\n",
    "\n",
    "**Q5. Why do you no longer use string-based exceptions?**\n",
    "\n",
    "**Ans:** String based exception were a feature of old versions of python but now have been decrypted and removed since python 3.0 primary because shifting to class based exeception handling.\n",
    "\n",
    "String based exception were less flexible and less informative with respect to class based exceptions. Also using class based exception leads to modular code and thus increased maintainability of code made code robust, easier to understand and debug.\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
